import { Text } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { getFilteredEvents } from '../../dummy-data';

import EventsList from '../../components/events/event-list';
import ResultTitle from '../../components/events/result-page';

export default function FilteredEvents() {
  const router = useRouter();

  const filterData = router.query.slug;

  if (!filterData) {
    return <Text>Loading...</Text>;
  }

  const filteredYear = filterData[0];
  const filteredMonth = filterData[1];

  const numYear = +filteredYear;
  const numMonth = +filteredMonth;

  if (
    isNaN(numYear) ||
    isNaN(numMonth) ||
    numYear > 2030 ||
    numYear < 2021 ||
    numMonth < 1 ||
    numMonth > 12
  ) {
    return <Text>Invalid filter. please adjust your value!</Text>;
  }

  const filteredEvents = getFilteredEvents({
    year: numYear,
    month: numMonth,
  });

  if (!filteredEvents || filteredEvents.length === 0) {
    return <Text>no events found for the chosen filter!</Text>;
  }
  const date = new Date(numYear, numMonth - 1);
  return (
    <div>
      <Head>
        <title>Single Post</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ResultTitle date={date} />
      <EventsList items={filteredEvents} />
    </div>
  );
}
