import Head from 'next/head';

export default function FilteredEvents() {
  return (
    <div>
      <Head>
        <title>Single Post</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1 className='text-2xl text-red-400'>filtered</h1>
    </div>
  );
}
