import Head from 'next/head';
import { useRouter } from 'next/router';
import { getAllEvents } from '../../dummy-data';
import EventsList from '../../components/events/event-list';
import EventsSearch from '../../components/events/events-search';

export default function AllEvents() {
  const router = useRouter();
  const events = getAllEvents();

  const findEventHandler = (year, month) => {
    const fullPath = `/events/${year}/${month}`;

    router.push(fullPath);
  };

  return (
    <div>
      <Head>
        <title>All Events</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <EventsSearch onSearch={findEventHandler} />
      <EventsList items={events} />
    </div>
  );
}
