import Head from 'next/head';
import { getAllEvents } from '../../dummy-data';
import EventsList from '../../components/events/event-list';

export default function AllEvents() {
  const events = getAllEvents();
  return (
    <div>
      <Head>
        <title>All Events</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <EventsList items={events} />
    </div>
  );
}
