import Head from 'next/head';

export default function AllEvents() {
  return (
    <div>
      <Head>
        <title>All Posts</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <h1 className='text-2xl text-red-400'>all events</h1>
    </div>
  );
}
