import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import EventsList from '../components/events/event-list';
import { getFeaturedEvents } from '../dummy-data';

export default function Home() {
  const featuredEvents = getFeaturedEvents();
  return (
    <Box>
      <Head>
        <title>Next Events</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box>
        <EventsList items={featuredEvents} />
      </Box>
    </Box>
  );
}
